name: Build task
on: [pull_request]

jobs:
  Build:
    name: Build task
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.JS
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: npm install
      run: npm install

    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm run test

    - name: Lint
      run: npm run lint
